version: 1
update_configs:
  - package_manager: "rust:cargo"
    directory: "."
    update_schedule: "live"
    target_branch: "master"
    default_reviewers:
      - "phaazon"
    default_assignees:
      - "phaazon"
    default_labels:
      - "dependency-update"
